<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LoggerService" Version="1.0.5" />
    <PackageReference Include="NLog" Version="6.0.4" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NLog">
      <HintPath>lib\NLog.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="FMDemodulator.cs" />
    <Compile Remove="IDemodulator.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RTLSDR.Common\RTLSDR.Common.csproj" />
  </ItemGroup>
</Project>