<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LibVLCSharp.MAUI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.3" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.70" />
    <PackageReference Include="SharpHook" Version="6.1.1" />
  </ItemGroup>

</Project>
