<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>DVBTTelevizor.MAUI</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AndroidEnable16KBPageSupport>true</AndroidEnable16KBPageSupport>

		<!-- Display name -->
		<ApplicationTitle>DVBT Televizor</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>net.petrjanousek.DVBTTelevizor</ApplicationId>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.22000.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.22000.0</TargetPlatformMinVersion>

	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('android'))">
		<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<!-- Versions
		Value 2025003 is too big for Windows
		-->
	<PropertyGroup Condition="$(TargetFramework.Contains('android'))">
		<ApplicationDisplayVersion>2025006</ApplicationDisplayVersion>
		<ApplicationVersion>2025006</ApplicationVersion>
		<VersionCode>2025006</VersionCode>
		<VersionName>2025006</VersionName>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('windows'))">
		<ApplicationDisplayVersion>2025</ApplicationDisplayVersion>
		<ApplicationVersion>2025</ApplicationVersion>
		<VersionCode>2025</VersionCode>
		<VersionName>2025</VersionName>
	</PropertyGroup>

	<PropertyGroup>
	  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.22000.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">

	  <AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
	  <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidPackageFormat>apk</AndroidPackageFormat>

	  <UseFastDeployment>true</UseFastDeployment>
	  <UseSharedRuntime>true</UseSharedRuntime>
	  <MandroidLinkMode>None</MandroidLinkMode>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
	  <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	  <AndroidPackageFormat>aab</AndroidPackageFormat>
	  <PublishTrimmed>True</PublishTrimmed>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" ForegroundFile="Resources\AppIcon\appicon.png" Color="#000000" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#000000" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Platforms\Android\NLog.config" />
	  <None Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Platforms\Android\NLog.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />
		<PackageReference Include="LibVLCSharp" Version="3.9.4" />
		<PackageReference Include="LoggerService" Version="1.0.5" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.100" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.100" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
		<PackageReference Include="NLog" Version="6.0.3" />
		<PackageReference Include="NLog.Targets.Network" Version="6.0.3" />
		<PackageReference Include="Plugin.InAppBilling" Version="9.1.0" />
		<PackageReference Include="RemoteAccessService" Version="1.0.4" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.1" />
		<PackageReference Include="VideoLAN.LibVLC.Android" Version="3.6.5" />
		<PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
	</ItemGroup>


	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
	  <PackageReference Include="LibVLCSharp.MAUI">
	    <Version>3.9.4</Version>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DVBTTelevizor.TV\DVBTTelevizor.TV.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('windows'))">
		<ProjectReference Include="..\LibVLCSharp.MAUI.Windows\LibVLCSharp.MAUI.Windows.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Menu.xaml.cs">
	    <DependentUpon>Menu.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\ChannelPage.xaml.cs">
	    <DependentUpon>ChannelPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\AboutPage.xaml.cs">
	    <DependentUpon>AboutPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\DriverPage.xaml.cs">
	    <DependentUpon>DriverPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\FrequencyPage.xaml.cs">
	    <DependentUpon>FrequencyPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TuningFrequencyPage.xaml.cs">
	    <DependentUpon>TuningFrequencyPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TuningSelectDVBTPage.xaml.cs">
	    <DependentUpon>TuningSelectDVBTPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TuningProgressPage.xaml.cs">
	    <DependentUpon>TuningProgressPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TuningFrequenciesPage.xaml.cs">
	    <DependentUpon>TuningFrequenciesPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TuningWelcomePage.xaml.cs">
	    <DependentUpon>TuningWelcomePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Platforms\Android\DVBTTelevizorConfiguration.cs">
	    <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
	  </Compile>
	  <Compile Update="Pages\SettingsPage.xaml.cs">
	    <DependentUpon>SettingsPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Platforms\Android\LoggingProvider.cs">
	    <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
	  </Compile>
	  <Compile Update="Platforms\Windows\PublicDirectoryProvider.cs">
	    <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
	  </Compile>
	</ItemGroup>

   <ItemGroup>
	 <AndroidAsset Include="Resources\Raw\Azerbaijani.lng" />
	 <AndroidAsset Include="Resources\Raw\Czech.lng" />
   </ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Menu.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="ImgButton.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\ChannelPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\AboutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\DriverPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\FrequencyPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TuningFrequencyPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TuningSelectDVBTPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TuningProgressPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TuningFrequenciesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TuningWelcomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Platforms\Windows\NLog.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
