<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RTLSDR.FM</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LoggerService" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RTLSDR.Common\RTLSDR.Common.csproj" />
  </ItemGroup>
</Project>
